name: python

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22

      - name: run ferret_plot pytest suite (in devshell)
        run: nix develop --command ./scripts/test_py.sh
